apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: k8s-service-watcher
  labels:
    app: service-watcher
  namespace: servicemesh
#    registerWithMesh: true

spec:
  selector:
    matchLabels:
      app: k8s-service-watcher
  template:
    metadata:
      labels:
        app: k8s-service-watcher
    spec:
      containers:
      - name: k8s-service-watcher
        image: dhpcontainreg.azurecr.io/core-app/k8s-service-watcher:v1
        imagePullPolicy: Always
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        volumeMounts:
        - name: kubeconfig
          mountPath: "/k8s-config"
          readOnly: true
        env:
          - name: wait_time
            value: 60
      restartPolicy: Always

      volumes:
      - name: kubeconfig
        secret:
          secretName: k8s-servicewatch-servicemesh-conf
