apiVersion: v1
kind: Service
metadata:
  name: servicemesh-consul
  labels:
    app: servicemesh
spec:
  type: LoadBalancer
  # todo: what is the targetPort attribute?
  ports:
  - name: talk-to-other-agents
    port: 8300
    targetPort: 8300
    nodePort: 31006