apiVersion: v1
kind: ServiceAccount
metadata:
  name: servicewatch
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: r_k8s_dhp_sa_servicewatch
rules:
- apiGroups: [""]
  resources: ["endpoints"]
  verbs: ["get","list","watch"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: servicewatch
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: r_k8s_dhp_sa_servicewatch
subjects:
- kind: ServiceAccount
  name: "servicewatch"
  namespace: servicemesh
